- name: Backup device configs
  gather_facts: false
  # connection: network_cli
  hosts: all
  tasks:
    - name: backup EOS configs
      eos_config:
        backup: yes
        backup_options:
          filename: "{{ SEMAPHORE_JOB_ID }}{{ inventory_hostname }}.txt"
          dir_path: "/app/backup/"
