- name: Backup device configs
  gather_facts: false
  # connection: network_cli
  hosts: all
  vars:
    time: "{{ lookup('pipe', 'date -d \"1 day ago\" +\"%Y%m%d\"') }}"
  tasks:
    - name: Backup EOS Configs
      eos_config:
        backup: yes
        backup_options:
          filename: "{{ time }}-{{ inventory_hostname }}.txt"
          dir_path: "/app/backup/"
