- name: Backup device configs
  gather_facts: false
  # connection: network_cli
  hosts: all
  tasks:
    - name: date and time demo
  hosts: all
  gather_facts: true
  tasks:
    - name: date and time
      ansible.builtin.debug:
        var: ansible_date_time
    - name: backup EOS configs
      eos_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_date_time }}{{ inventory_hostname }}.txt"
          dir_path: "/app/backup/"
