---
- name: Use CLI to enable eAPI
  hosts: all
  connection: network_cli
  gather_facts: true
  
  tasks:
    - name: Enable eAPI with HTTP at port 80
      eos_eapi:
        state: started
        http: true
        http_port: 80
