---
- hosts: all
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
    
    - name: Upgrade all packages
      apt:
        upgrade: yes
        
    - name: Clean up unused packages
      apt:
        autoremove: yes    

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot server if required
      reboot:
        msg: "Rebooting because of package updates"
        connect_timeout: 5
      when: reboot_required.stat.exists
