---
- name: Update Debian Linux
  become: yes
  
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoclean: yes
