---
- hosts: all
  gather_facts: true
  vars:
      ansible_port: 5985
      ansible_winrm_scheme: http
      ansible_winrm_send_cbt: no
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Install all updates and reboot if needed
    ansible.windows.win_updates:
      category_names: '*'
      reboot: true
      log_path: C:\ansible_wu.txt

